# Generated by Django 4.2.2 on 2023-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth_date',
            field=models.DateField(null=True),
        ),
    ]
